### ISSUE TITLE
Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by spencer-mize** [Uberspace/icingaweb2-module-netboximport#1]
Cannot run an import from NetBox to Icingaweb2:

```
#0 /usr/share/icingaweb2/modules/netboximport/library/Netboximport/ProvidedHook/Director/ImportSource.php(93): Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(Integer, String, String, Integer, Array)
#1 /usr/share/icingaweb2/modules/netboximport/library/Netboximport/ProvidedHook/Director/ImportSource.php(167): Icinga\Module\Netboximport\ProvidedHook\Director\ImportSource->fetchInterfaces()
#2 /usr/share/icingaweb2/modules/director/library/Director/Web/Table/ImportsourceHookTable.php(109): Icinga\Module\Netboximport\ProvidedHook\Director\ImportSource->fetchData()
#3 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Web/Table/SimpleQueryBasedTable.php(29): Icinga\Module\Director\Web\Table\ImportsourceHookTable->prepareQuery()
#4 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Web/Table/SimpleQueryBasedTable.php(15): dipl\Web\Table\SimpleQueryBasedTable->getQuery()
#5 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Web/Table/QueryBasedTable.php(56): dipl\Web\Table\SimpleQueryBasedTable->getPaginationAdapter()
#6 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Web/Table/QueryBasedTable.php(237): dipl\Web\Table\QueryBasedTable->getPaginator(Object(dipl\Web\Url))
#7 /usr/share/icingaweb2/modules/director/application/controllers/ImportsourceController.php(74): dipl\Web\Table\QueryBasedTable->renderTo(Object(Icinga\Module\Director\Controllers\ImportsourceController))
#8 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Director\Controllers\ImportsourceController->previewAction()
#9 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch(String)
#10 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#11 /usr/share/php/Icinga/Application/Web.php(409): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#12 /usr/share/php/Icinga/Application/webrouter.php(104): Icinga\Application\Web->dispatch()
#13 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#14 {main}
```

Settings:
![image](https://user-images.githubusercontent.com/642637/41749476-90346bfa-7584-11e8-8067-f7bc97998311.png)

**Comment by luto** [comment]
Sorry to hear that the importer is crashing on your site. Can you please add your netbox as well as icinga2 version to the report, for completeness? I am going to prepare a bug report template soon, so github actually asks those things.

Also, if possible, please share the output of http://10.0.15.127:32768/api/ipam/ip-addresses/, as the it seems like netbox didn't return a list.

Thank you!

**Comment by spencer-mize** [comment]
Hey no problem - thanks for the quick response!

Icinga: v2.8.4-759-geblf37905
Ubuntu: 18.04 / 4.15.0-23-generic
Netbox: 2.3.4

Output (incl. some redactions):
<details>
  <summary>Click to expand</summary>

```
HTTP 200 OK
Allow: GET, POST, HEAD, OPTIONS
Content-Type: application/json
Vary: Accept

{
    "count": 41,
    "next": null,
    "previous": null,
    "results": [
        {
            "id": 3,
            "family": 4,
            "address": "10.0.10.1/24",
            "vrf": null,
            "tenant": null,
            "status": {
                "value": 1,
                "label": "Active"
            },
            "role": null,
            "interface": {
                "id": 101,
                "url": "http://10.0.15.127:32768/api/dcim/interfaces/101/",
                "device": {
                    "id": 11,
                    "url": "http://10.0.15.127:32768/api/dcim/devices/11/",
                    "name": "redacted",
                    "display_name": "redacted"
                },
                "virtual_machine": null,
                "name": "GigabitEthernet1/1"
            },
            "description": "",
            "nat_inside": null,
            "nat_outside": null,
            "custom_fields": {},
            "created": "2018-06-15",
            "last_updated": "2018-06-15T20:44:31.243804Z"
        },
        {
            "id": 2,
            "family": 4,
            "address": "10.0.10.2/24",
            "vrf": null,
            "tenant": null,
            "status": {
                "value": 1,
                "label": "Active"
            },
            "role": null,
            "interface": {
                "id": 157,
                "url": "http://10.0.15.127:32768/api/dcim/interfaces/157/",
                "device": {
                    "id": 13,
                    "url": "http://10.0.15.127:32768/api/dcim/devices/13/",
                    "name": "redacted",
                    "display_name": "redacted"
                },
                "virtual_machine": null,
                "name": "GigabitEthernet1/1/1"
            },
            "description": "",
            "nat_inside": null,
            "nat_outside": null,
            "custom_fields": {},
            "created": "2018-06-15",
            "last_updated": "2018-06-15T20:41:12.865898Z"
        },
        {
            "id": 5,
            "family": 4,
            "address": "10.0.10.3/24",
            "vrf": null,
            "tenant": null,
            "status": {
                "value": 1,
                "label": "Active"
            },
            "role": null,
            "interface": {
                "id": 185,
                "url": "http://10.0.15.127:32768/api/dcim/interfaces/185/",
                "device": {
                    "id": 14,
                    "url": "http://10.0.15.127:32768/api/dcim/devices/14/",
                    "name": "redacted",
                    "display_name": "redacted"
                },
                "virtual_machine": null,
                "name": "GigabitEthernet1/1/1"
            },
            "description": "",
            "nat_inside": null,
            "nat_outside": null,
            "custom_fields": {},
            "created": "2018-06-15",
            "last_updated": "2018-06-15T20:48:54.643228Z"
        },
        {
            "id": 16,
            "family": 4,
            "address": "10.0.10.4/24",
            "vrf": null,
            "tenant": null,
            "status": {
                "value": 1,
                "label": "Active"
            },
            "role": null,
            "interface": {
                "id": 333,
                "url": "http://10.0.15.127:32768/api/dcim/interfaces/333/",
                "device": {
                    "id": 19,
                    "url": "http://10.0.15.127:32768/api/dcim/devices/19/",
                    "name": "Portable-SW1",
                    "display_name": "Portable-SW1"
                },
                "virtual_machine": null,
                "name": "GigabitEthernet1/9"
            },
            "description": "",
            "nat_inside": null,
            "nat_outside": null,
            "custom_fields": {},
            "created": "2018-06-15",
            "last_updated": "2018-06-15T21:20:25.579594Z"
        },
        {
            "id": 7,
            "family": 4,
            "address": "10.0.10.5/24",
            "vrf": null,
            "tenant": null,
            "status": {
                "value": 1,
                "label": "Active"
            },
            "role": null,
            "interface": {
                "id": 338,
                "url": "http://10.0.15.127:32768/api/dcim/interfaces/338/",
                "device": {
                    "id": 20,
                    "url": "http://10.0.15.127:32768/api/dcim/devices/20/",
                    "name": "redacted",
                    "display_name": "redacted"
                },
                "virtual_machine": null,
                "name": "Port2"
            },
            "description": "",
            "nat_inside": null,
            "nat_outside": null,
            "custom_fields": {},
            "created": "2018-06-15",
            "last_updated": "2018-06-15T21:28:31.095361Z"
        },
        {
            "id": 37,
            "family": 4,
            "address": "10.0.10.6/24",
            "vrf": null,
            "tenant": null,
            "status": {
                "value": 1,
                "label": "Active"
            },
            "role": null,
            "interface": {
                "id": 371,
                "url": "http://10.0.15.127:32768/api/dcim/interfaces/371/",
                "device": {
                    "id": 26,
                    "url": "http://10.0.15.127:32768/api/dcim/devices/26/",
                    "name": "Franklin",
                    "display_name": "Franklin"
                },
                "virtual_machine": null,
                "name": "iLo"
            },
            "description": "",
            "nat_inside": null,
            "nat_outside": null,
            "custom_fields": {},
            "created": "2018-06-21",
            "last_updated": "2018-06-21T22:18:25.209747Z"
        },
        {
            "id": 39,
            "family": 4,
            "address": "10.0.10.7/24",
            "vrf": null,
            "tenant": null,
            "status": {
                "value": 1,
                "label": "Active"
            },
            "role": null,
            "interface": {
                "id": 373,
                "url": "http://10.0.15.127:32768/api/virtualization/interfaces/373/",
                "device": null,
                "virtual_machine": {
                    "id": 5,
                    "url": "http://10.0.15.127:32768/api/virtualization/virtual-machines/5/",
                    "name": "Hamilton"
                },
                "name": "eth0"
            },
            "description": "",
            "nat_inside": null,
            "nat_outside": null,
            "custom_fields": {},
            "created": "2018-06-21",
            "last_updated": "2018-06-21T22:30:17.975866Z"
        },
        {
            "id": 38,
            "family": 4,
            "address": "10.0.10.8/24",
            "vrf": null,
            "tenant": null,
            "status": {
                "value": 1,
                "label": "Active"
            },
            "role": null,
            "interface": {
                "id": 372,
                "url": "http://10.0.15.127:32768/api/dcim/interfaces/372/",
                "device": {
                    "id": 27,
                    "url": "http://10.0.15.127:32768/api/dcim/devices/27/",
                    "name": "Adams",
                    "display_name": "Adams"
                },
                "virtual_machine": null,
                "name": "iLo"
            },
            "description": "",
            "nat_inside": null,
            "nat_outside": null,
            "custom_fields": {},
            "created": "2018-06-21",
            "last_updated": "2018-06-21T22:19:01.043009Z"
        },
        {
            "id": 11,
            "family": 4,
            "address": "10.0.10.9/24",
            "vrf": null,
            "tenant": null,
            "status": {
                "value": 1,
                "label": "Active"
            },
            "role": null,
            "interface": null,
            "description": "",
            "nat_inside": null,
            "nat_outside": null,
            "custom_fields": {},
            "created": "2018-06-15",
            "last_updated": "2018-06-15T20:43:09.477641Z"
        },
        {
            "id": 35,
            "family": 4,
            "address": "10.0.10.10/24",
            "vrf": null,
            "tenant": null,
            "status": {
                "value": 1,
                "label": "Active"
            },
            "role": null,
            "interface": {
                "id": 369,
                "url": "http://10.0.15.127:32768/api/virtualization/interfaces/369/",
                "device": null,
                "virtual_machine": {
                    "id": 4,
                    "url": "http://10.0.15.127:32768/api/virtualization/virtual-machines/4/",
                    "name": "Gideon"
                },
                "name": "Port 2"
            },
            "description": "",
            "nat_inside": null,
            "nat_outside": null,
            "custom_fields": {},
            "created": "2018-06-21",
            "last_updated": "2018-06-21T22:16:03.313557Z"
        },
        {
            "id": 23,
            "family": 4,
            "address": "10.0.10.19/24",
            "vrf": null,
            "tenant": null,
            "status": {
                "value": 1,
                "label": "Active"
            },
            "role": null,
            "interface": {
                "id": 346,
                "url": "http://10.0.15.127:32768/api/dcim/interfaces/346/",
                "device": {
                    "id": 25,
                    "url": "http://10.0.15.127:32768/api/dcim/devices/25/",
                    "name": "Cisco LAN Controller",
                    "display_name": "Cisco LAN Controller"
                },
                "virtual_machine": null,
                "name": "Port 2"
            },
            "description": "",
            "nat_inside": null,
            "nat_outside": null,
            "custom_fields": {},
            "created": "2018-06-21",
            "last_updated": "2018-06-21T21:39:05.379126Z"
        },
        {
            "id": 31,
            "family": 4,
            "address": "10.0.10.30/24",
            "vrf": null,
            "tenant": null,
            "status": {
                "value": 1,
                "label": "Active"
            },
            "role": null,
            "interface": {
                "id": 366,
                "url": "http://10.0.15.127:32768/api/virtualization/interfaces/366/",
                "device": null,
                "virtual_machine": {
                    "id": 3,
                    "url": "http://10.0.15.127:32768/api/virtualization/virtual-machines/3/",
                    "name": "Hercules"
                },
                "name": "eth1"
            },
            "description": "",
            "nat_inside": null,
            "nat_outside": null,
            "custom_fields": {},
            "created": "2018-06-21",
            "last_updated": "2018-06-21T22:13:44.087997Z"
        },
        {
            "id": 15,
            "family": 4,
            "address": "10.0.10.51/24",
            "vrf": null,
            "tenant": null,
            "status": {
                "value": 3,
                "label": "Deprecated"
            },
            "role": null,
            "interface": {
                "id": 269,
                "url": "http://10.0.15.127:32768/api/dcim/interfaces/269/",
                "device": {
                    "id": 17,
                    "url": "http://10.0.15.127:32768/api/dcim/devices/17/",
                    "name": "redacted",
                    "display_name": "redacted"
                },
                "virtual_machine": null,
                "name": "GigabitEthernet1/1/1"
            },
            "description": "",
            "nat_inside": null,
            "nat_outside": null,
            "custom_fields": {},
            "created": "2018-06-15",
            "last_updated": "2018-06-15T21:18:04.248658Z"
        },
        {
            "id": 14,
            "family": 4,
            "address": "10.0.10.52/24",
            "vrf": null,
            "tenant": null,
            "status": {
                "value": 1,
                "label": "Active"
            },
            "role": null,
            "interface": {
                "id": 316,
                "url": "http://10.0.15.127:32768/api/dcim/interfaces/316/",
                "device": {
                    "id": 18,
                    "url": "http://10.0.15.127:32768/api/dcim/devices/18/",
                    "name": "redacted",
                    "display_name": "redacted"
                },
                "virtual_machine": null,
                "name": "GigabitEthernet1/0/49"
            },
            "description": "",
            "nat_inside": null,
            "nat_outside": null,
            "custom_fields": {},
            "created": "2018-06-15",
            "last_updated": "2018-06-15T21:17:25.499435Z"
        },
        {
            "id": 12,
            "family": 4,
            "address": "10.0.10.101/24",
            "vrf": null,
            "tenant": null,
            "status": {
                "value": 1,
                "label": "Active"
            },
            "role": null,
            "interface": {
                "id": 213,
                "url": "http://10.0.15.127:32768/api/dcim/interfaces/213/",
                "device": {
                    "id": 15,
                    "url": "http://10.0.15.127:32768/api/dcim/devices/15/",
                    "name": "redacted",
                    "display_name": "redacted"
                },
                "virtual_machine": null,
                "name": "GigabitEthernet1/1/1"
            },
            "description": "",
            "nat_inside": null,
            "nat_outside": null,
            "custom_fields": {},
            "created": "2018-06-15",
            "last_updated": "2018-06-15T20:45:38.368258Z"
        },
        {
            "id": 13,
            "family": 4,
            "address": "10.0.10.151/24",
            "vrf": null,
            "tenant": null,
            "status": {
                "value": 1,
                "label": "Active"
            },
            "role": null,
            "interface": {
                "id": 234,
                "url": "http://10.0.15.127:32768/api/dcim/interfaces/234/",
                "device": {
                    "id": 16,
                    "url": "http://10.0.15.127:32768/api/dcim/devices/16/",
                    "name": "redacted",
                    "display_name": "redacted"
                },
                "virtual_machine": null,
                "name": "GigabitEthernet1/0/25"
            },
            "description": "",
            "nat_inside": null,
            "nat_outside": null,
            "custom_fields": {},
            "created": "2018-06-15",
            "last_updated": "2018-06-15T20:50:53.758769Z"
        },
        {
            "id": 32,
            "family": 4,
            "address": "10.0.13.3/24",
            "vrf": null,
            "tenant": null,
            "status": {
                "value": 1,
                "label": "Active"
            },
            "role": null,
            "interface": {
                "id": 367,
                "url": "http://10.0.15.127:32768/api/virtualization/interfaces/367/",
                "device": null,
                "virtual_machine": {
                    "id": 3,
                    "url": "http://10.0.15.127:32768/api/virtualization/virtual-machines/3/",
                    "name": "Hercules"
                },
                "name": "eth2"
            },
            "description": "",
            "nat_inside": null,
            "nat_outside": null,
            "custom_fields": {},
            "created": "2018-06-21",
            "last_updated": "2018-06-21T22:13:56.355277Z"
        },
        {
            "id": 45,
            "family": 4,
            "address": "10.0.13.5/24",
            "vrf": null,
            "tenant": null,
            "status": {
                "value": 1,
                "label": "Active"
            },
            "role": null,
            "interface": {
                "id": 383,
                "url": "http://10.0.15.127:32768/api/dcim/interfaces/383/",
                "device": {
                    "id": 31,
                    "url": "http://10.0.15.127:32768/api/dcim/devices/31/",
                    "name": "redacted",
                    "display_name": "redacted"
                },
                "virtual_machine": null,
                "name": "WAN"
            },
            "description": "",
            "nat_inside": null,
            "nat_outside": null,
            "custom_fields": {},
            "created": "2018-06-21",
            "last_updated": "2018-06-21T23:11:53.322451Z"
        },
        {
            "id": 46,
            "family": 4,
            "address": "10.0.13.7/24",
            "vrf": null,
            "tenant": null,
            "status": {
                "value": 1,
                "label": "Active"
            },
            "role": null,
            "interface": {
                "id": 381,
                "url": "http://10.0.15.127:32768/api/dcim/interfaces/381/",
                "device": {
                    "id": 30,
                    "url": "http://10.0.15.127:32768/api/dcim/devices/30/",
                    "name": "redacted",
                    "display_name": "redacted"
                },
                "virtual_machine": null,
                "name": "WAN"
            },
            "description": "",
            "nat_inside": null,
            "nat_outside": null,
            "custom_fields": {},
            "created": "2018-06-21",
            "last_updated": "2018-06-21T23:12:15.320036Z"
        },
        {
            "id": 47,
            "family": 4,
            "address": "10.0.13.8/24",
            "vrf": null,
            "tenant": null,
            "status": {
                "value": 1,
                "label": "Active"
            },
            "role": null,
            "interface": {
                "id": 385,
                "url": "http://10.0.15.127:32768/api/dcim/interfaces/385/",
                "device": {
                    "id": 32,
                    "url": "http://10.0.15.127:32768/api/dcim/devices/32/",
                    "name": "redacted",
                    "display_name": "redacted"
                },
                "virtual_machine": null,
                "name": "WAN"
            },
            "description": "",
            "nat_inside": null,
            "nat_outside": null,
            "custom_fields": {},
            "created": "2018-06-21",
            "last_updated": "2018-06-21T23:12:31.133992Z"
        },
        {
            "id": 44,
            "family": 4,
            "address": "10.0.13.9/24",
            "vrf": null,
            "tenant": null,
            "status": {
                "value": 1,
                "label": "Active"
            },
            "role": null,
            "interface": {
                "id": 387,
                "url": "http://10.0.15.127:32768/api/dcim/interfaces/387/",
                "device": {
                    "id": 33,
                    "url": "http://10.0.15.127:32768/api/dcim/devices/33/",
                    "name": "redacted",
                    "display_name": "redacted"
                },
                "virtual_machine": null,
                "name": "WAN"
            },
            "description": "",
            "nat_inside": null,
            "nat_outside": null,
            "custom_fields": {},
            "created": "2018-06-21",
            "last_updated": "2018-06-21T23:11:39.073468Z"
        },
        {
            "id": 42,
            "family": 4,
            "address": "10.0.13.10/24",
            "vrf": null,
            "tenant": null,
            "status": {
                "value": 1,
                "label": "Active"
            },
            "role": null,
            "interface": {
                "id": 379,
                "url": "http://10.0.15.127:32768/api/dcim/interfaces/379/",
                "device": {
                    "id": 29,
                    "url": "http://10.0.15.127:32768/api/dcim/devices/29/",
                    "name": "redacted",
                    "display_name": "redacted"
                },
                "virtual_machine": null,
                "name": "WAN"
            },
            "description": "",
            "nat_inside": null,
            "nat_outside": null,
            "custom_fields": {},
            "created": "2018-06-21",
            "last_updated": "2018-06-21T23:10:47.305646Z"
        },
        {
            "id": 43,
            "family": 4,
            "address": "10.0.13.12/24",
            "vrf": null,
            "tenant": null,
            "status": {
                "value": 1,
                "label": "Active"
            },
            "role": null,
            "interface": {
                "id": 389,
                "url": "http://10.0.15.127:32768/api/dcim/interfaces/389/",
                "device": {
                    "id": 34,
                    "url": "http://10.0.15.127:32768/api/dcim/devices/34/",
                    "name": "redacted",
                    "display_name": "redacted"
                },
                "virtual_machine": null,
                "name": "WAN"
            },
            "description": "",
            "nat_inside": null,
            "nat_outside": null,
            "custom_fields": {},
            "created": "2018-06-21",
            "last_updated": "2018-06-21T23:11:22.443916Z"
        },
        {
            "id": 27,
            "family": 4,
            "address": "10.0.13.100/24",
            "vrf": null,
            "tenant": null,
            "status": {
                "value": 1,
                "label": "Active"
            },
            "role": null,
            "interface": {
                "id": 362,
                "url": "http://10.0.15.127:32768/api/virtualization/interfaces/362/",
                "device": null,
                "virtual_machine": {
                    "id": 1,
                    "url": "http://10.0.15.127:32768/api/virtualization/virtual-machines/1/",
                    "name": "Jefferson"
                },
                "name": "Ethernet (Phones - 13)"
            },
            "description": "",
            "nat_inside": null,
            "nat_outside": null,
            "custom_fields": {},
            "created": "2018-06-21",
            "last_updated": "2018-06-21T21:58:57.100709Z"
        },
        {
            "id": 40,
            "family": 4,
            "address": "10.0.14.5/24",
            "vrf": null,
            "tenant": null,
            "status": {
                "value": 1,
                "label": "Active"
            },
            "role": null,
            "interface": {
                "id": 374,
                "url": "http://10.0.15.127:32768/api/dcim/interfaces/374/",
                "device": {
                    "id": 28,
                    "url": "http://10.0.15.127:32768/api/dcim/devices/28/",
                    "name": "Washington",
                    "display_name": "Washington"
                },
                "virtual_machine": null,
                "name": "Port 1"
            },
            "description": "",
            "nat_inside": null,
            "nat_outside": null,
            "custom_fields": {},
            "created": "2018-06-21",
            "last_updated": "2018-06-21T22:34:38.085535Z"
        },
        {
            "id": 24,
            "family": 4,
            "address": "10.0.15.19/24",
            "vrf": null,
            "tenant": null,
            "status": {
                "value": 1,
                "label": "Active"
            },
            "role": null,
            "interface": {
                "id": 345,
                "url": "http://10.0.15.127:32768/api/dcim/interfaces/345/",
                "device": {
                    "id": 25,
                    "url": "http://10.0.15.127:32768/api/dcim/devices/25/",
                    "name": "Cisco LAN Controller",
                    "display_name": "Cisco LAN Controller"
                },
                "virtual_machine": null,
                "name": "Port 1"
            },
            "description": "",
            "nat_inside": null,
            "nat_outside": null,
            "custom_fields": {},
            "created": "2018-06-21",
            "last_updated": "2018-06-21T21:42:09.625196Z"
        },
        {
            "id": 29,
            "family": 4,
            "address": "10.0.15.21/24",
            "vrf": null,
            "tenant": null,
            "status": {
                "value": 1,
                "label": "Active"
            },
            "role": null,
            "interface": {
                "id": 357,
                "url": "http://10.0.15.127:32768/api/dcim/interfaces/357/",
                "device": {
                    "id": 26,
                    "url": "http://10.0.15.127:32768/api/dcim/devices/26/",
                    "name": "Franklin",
                    "display_name": "Franklin"
                },
                "virtual_machine": null,
                "name": "Port 1"
            },
            "description": "",
            "nat_inside": null,
            "nat_outside": null,
            "custom_fields": {},
            "created": "2018-06-21",
            "last_updated": "2018-06-21T22:04:03.497192Z"
        },
        {
            "id": 26,
            "family": 4,
            "address": "10.0.15.22/24",
            "vrf": null,
            "tenant": null,
            "status": {
                "value": 1,
                "label": "Active"
            },
            "role": null,
            "interface": {
                "id": 364,
                "url": "http://10.0.15.127:32768/api/virtualization/interfaces/364/",
                "device": null,
                "virtual_machine": {
                    "id": 1,
                    "url": "http://10.0.15.127:32768/api/virtualization/virtual-machines/1/",
                    "name": "Jefferson"
                },
                "name": "Ethernet (Employee - 15)"
            },
            "description": "",
            "nat_inside": null,
            "nat_outside": null,
            "custom_fields": {},
            "created": "2018-06-21",
            "last_updated": "2018-06-21T21:58:43.758747Z"
        },
        {
            "id": 30,
            "family": 4,
            "address": "10.0.15.26/24",
            "vrf": null,
            "tenant": null,
            "status": {
                "value": 1,
                "label": "Active"
            },
            "role": null,
            "interface": {
                "id": 353,
                "url": "http://10.0.15.127:32768/api/dcim/interfaces/353/",
                "device": {
                    "id": 27,
                    "url": "http://10.0.15.127:32768/api/dcim/devices/27/",
                    "name": "Adams",
                    "display_name": "Adams"
                },
                "virtual_machine": null,
                "name": "Port 1"
            },
            "description": "",
            "nat_inside": null,
            "nat_outside": null,
            "custom_fields": {},
            "created": "2018-06-21",
            "last_updated": "2018-06-21T22:05:04.129470Z"
        },
        {
            "id": 41,
            "family": 4,
            "address": "10.0.15.28/24",
            "vrf": null,
            "tenant": null,
            "status": {
                "value": 1,
                "label": "Active"
            },
            "role": null,
            "interface": {
                "id": 375,
                "url": "http://10.0.15.127:32768/api/dcim/interfaces/375/",
                "device": {
                    "id": 28,
                    "url": "http://10.0.15.127:32768/api/dcim/devices/28/",
                    "name": "Washington",
                    "display_name": "Washington"
                },
                "virtual_machine": null,
                "name": "Port 2"
            },
            "description": "",
            "nat_inside": null,
            "nat_outside": null,
            "custom_fields": {},
            "created": "2018-06-21",
            "last_updated": "2018-06-21T22:34:48.730882Z"
        },
        {
            "id": 25,
            "family": 4,
            "address": "10.0.15.29/24",
            "vrf": null,
            "tenant": null,
            "status": {
                "value": 1,
                "label": "Active"
            },
            "role": null,
            "interface": {
                "id": 361,
                "url": "http://10.0.15.127:32768/api/virtualization/interfaces/361/",
                "device": null,
                "virtual_machine": {
                    "id": 2,
                    "url": "http://10.0.15.127:32768/api/virtualization/virtual-machines/2/",
                    "name": "Madison"
                },
                "name": "Ethernet 1"
            },
            "description": "",
            "nat_inside": null,
            "nat_outside": null,
            "custom_fields": {},
            "created": "2018-06-21",
            "last_updated": "2018-06-21T22:06:38.072135Z"
        },
        {
            "id": 34,
            "family": 4,
            "address": "10.0.15.30/24",
            "vrf": null,
            "tenant": null,
            "status": {
                "value": 1,
                "label": "Active"
            },
            "role": null,
            "interface": {
                "id": 368,
                "url": "http://10.0.15.127:32768/api/virtualization/interfaces/368/",
                "device": null,
                "virtual_machine": {
                    "id": 4,
                    "url": "http://10.0.15.127:32768/api/virtualization/virtual-machines/4/",
                    "name": "Gideon"
                },
                "name": "Port 1"
            },
            "description": "",
            "nat_inside": null,
            "nat_outside": null,
            "custom_fields": {},
            "created": "2018-06-21",
            "last_updated": "2018-06-21T22:15:53.855908Z"
        },
        {
            "id": 33,
            "family": 4,
            "address": "10.0.15.127/24",
            "vrf": null,
            "tenant": null,
            "status": {
                "value": 1,
                "label": "Active"
            },
            "role": null,
            "interface": {
                "id": 365,
                "url": "http://10.0.15.127:32768/api/virtualization/interfaces/365/",
                "device": null,
                "virtual_machine": {
                    "id": 3,
                    "url": "http://10.0.15.127:32768/api/virtualization/virtual-machines/3/",
                    "name": "Hercules"
                },
                "name": "eth0"
            },
            "description": "",
            "nat_inside": null,
            "nat_outside": null,
            "custom_fields": {},
            "created": "2018-06-21",
            "last_updated": "2018-06-21T22:12:59.561618Z"
        },
        {
            "id": 19,
            "family": 4,
            "address": "10.0.100.3/24",
            "vrf": null,
            "tenant": null,
            "status": {
                "value": 1,
                "label": "Active"
            },
            "role": null,
            "interface": {
                "id": 344,
                "url": "http://10.0.15.127:32768/api/dcim/interfaces/344/",
                "device": {
                    "id": 24,
                    "url": "http://10.0.15.127:32768/api/dcim/devices/24/",
                    "name": "Events Center HVAC",
                    "display_name": "Events Center HVAC"
                },
                "virtual_machine": null,
                "name": "NIC 1"
            },
            "description": "",
            "nat_inside": null,
            "nat_outside": null,
            "custom_fields": {},
            "created": "2018-06-21",
            "last_updated": "2018-06-21T20:48:59.423006Z"
        },
        {
            "id": 21,
            "family": 4,
            "address": "10.0.100.4/24",
            "vrf": null,
            "tenant": null,
            "status": {
                "value": 1,
                "label": "Active"
            },
            "role": null,
            "interface": {
                "id": 343,
                "url": "http://10.0.15.127:32768/api/dcim/interfaces/343/",
                "device": {
                    "id": 23,
                    "url": "http://10.0.15.127:32768/api/dcim/devices/23/",
                    "name": "redacted",
                    "display_name": "redacted"
                },
                "virtual_machine": null,
                "name": "NIC 1"
            },
            "description": "",
            "nat_inside": null,
            "nat_outside": null,
            "custom_fields": {},
            "created": "2018-06-21",
            "last_updated": "2018-06-21T20:50:26.342714Z"
        },
        {
            "id": 22,
            "family": 4,
            "address": "10.0.100.6/24",
            "vrf": null,
            "tenant": null,
            "status": {
                "value": 1,
                "label": "Active"
            },
            "role": null,
            "interface": {
                "id": 342,
                "url": "http://10.0.15.127:32768/api/dcim/interfaces/342/",
                "device": {
                    "id": 22,
                    "url": "http://10.0.15.127:32768/api/dcim/devices/22/",
                    "name": "redacted",
                    "display_name": "redacted"
                },
                "virtual_machine": null,
                "name": "NIC 1"
            },
            "description": "",
            "nat_inside": null,
            "nat_outside": null,
            "custom_fields": {},
            "created": "2018-06-21",
            "last_updated": "2018-06-21T21:25:00.318259Z"
        },
        {
            "id": 20,
            "family": 4,
            "address": "10.0.100.15/24",
            "vrf": null,
            "tenant": null,
            "status": {
                "value": 1,
                "label": "Active"
            },
            "role": null,
            "interface": {
                "id": 341,
                "url": "http://10.0.15.127:32768/api/dcim/interfaces/341/",
                "device": {
                    "id": 21,
                    "url": "http://10.0.15.127:32768/api/dcim/devices/21/",
                    "name": "redacted",
                    "display_name": "redacted"
                },
                "virtual_machine": null,
                "name": "NIC 1"
            },
            "description": "",
            "nat_inside": null,
            "nat_outside": null,
            "custom_fields": {},
            "created": "2018-06-21",
            "last_updated": "2018-06-21T20:49:19.315257Z"
        },
        {
            "id": 36,
            "family": 4,
            "address": "10.0.151.5/24",
            "vrf": null,
            "tenant": null,
            "status": {
                "value": 1,
                "label": "Active"
            },
            "role": null,
            "interface": {
                "id": 370,
                "url": "http://10.0.15.127:32768/api/virtualization/interfaces/370/",
                "device": null,
                "virtual_machine": {
                    "id": 4,
                    "url": "http://10.0.15.127:32768/api/virtualization/virtual-machines/4/",
                    "name": "Gideon"
                },
                "name": "Port 3"
            },
            "description": "",
            "nat_inside": null,
            "nat_outside": null,
            "custom_fields": {},
            "created": "2018-06-21",
            "last_updated": "2018-06-21T22:16:13.476463Z"
        },
        {
            "id": 17,
            "family": 4,
            "address": "redacted",
            "vrf": null,
            "tenant": null,
            "status": {
                "value": 1,
                "label": "Active"
            },
            "role": null,
            "interface": {
                "id": 339,
                "url": "http://10.0.15.127:32768/api/dcim/interfaces/339/",
                "device": {
                    "id": 20,
                    "url": "http://10.0.15.127:32768/api/dcim/devices/20/",
                    "name": "pfSense",
                    "display_name": "pfSense"
                },
                "virtual_machine": null,
                "name": "Port3"
            },
            "description": "",
            "nat_inside": null,
            "nat_outside": null,
            "custom_fields": {},
            "created": "2018-06-15",
            "last_updated": "2018-06-15T21:27:10.182518Z"
        },
        {
            "id": 28,
            "family": 4,
            "address": "redacted",
            "vrf": null,
            "tenant": null,
            "status": {
                "value": 1,
                "label": "Active"
            },
            "role": null,
            "interface": {
                "id": 363,
                "url": "http://10.0.15.127:32768/api/virtualization/interfaces/363/",
                "device": null,
                "virtual_machine": {
                    "id": 1,
                    "url": "http://10.0.15.127:32768/api/virtualization/virtual-machines/1/",
                    "name": "Jefferson"
                },
                "name": "Ethernet (SIP)"
            },
            "description": "",
            "nat_inside": null,
            "nat_outside": null,
            "custom_fields": {},
            "created": "2018-06-21",
            "last_updated": "2018-06-21T21:59:40.398176Z"
        },
        {
            "id": 18,
            "family": 4,
            "address": "redacted",
            "vrf": null,
            "tenant": null,
            "status": {
                "value": 1,
                "label": "Active"
            },
            "role": null,
            "interface": {
                "id": 337,
                "url": "http://10.0.15.127:32768/api/dcim/interfaces/337/",
                "device": {
                    "id": 20,
                    "url": "http://10.0.15.127:32768/api/dcim/devices/20/",
                    "name": "redacted",
                    "display_name": "redacted"
                },
                "virtual_machine": null,
                "name": "Port1"
            },
            "description": "",
            "nat_inside": null,
            "nat_outside": null,
            "custom_fields": {},
            "created": "2018-06-15",
            "last_updated": "2018-06-15T21:28:54.390814Z"
        }
    ]
}
```

</details>

**Comment by spencer-mize** [comment]
Good call on the "netbox didn't return a list" - I didn't notice the Base URL field needed the /api. Works now - you might just consider adjusting the verbiage to "API URL" or something similar. Anyway, we'll call this closed!
